workflows:
  android-build:
    name: "إصدار أندرويد"
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: "تنزيل الحزم"
        script: flutter pub get
      - name: "بناء APK"
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
